### ISSUE TITLE
[错误报告] 1.19中无法正常使用

### ISSUE THREAD

**Issue by vlssu** [CaaMoe/MultiLogin#47]
### BUG描述

![image](https://user-images.githubusercontent.com/43847794/174467388-2f8da3f6-3a21-4d4f-83aa-b891784e74bf.png)
直接提示，连接中止，但我用外置登录直接进入服务器是可以进入的
奇怪的是控制台并没有输出日志
应该是 `velocity` 用了新的密钥执行标准，但我已设置为false但依旧没有任何用。
我也在那边提问了（只使用外置登录的场景）
https://github.com/PaperMC/Velocity/issues/755

### MultiLogin版本

0.3.14

### 系统架构

linux/amd64

### 配置文件

```
###################################
#       MultiLogin
#              --config
###################################

# 在这里，设置所有的 Yggdrasil 账户验证服务器。
services:

  # 这是一个示例配置：
  # 节点名称 'demo' 作为混合验证系统区分 Yggdrasil 验证服务器唯一性的凭据，设置好后请不要随意的去改动它，
  # 随意的更改节点名称将会导致二次验证系统无法验明用户身份而拒绝用户的登入请求。
  # 可以仿写此节点用来添加新的 Yggdrasil 账户验证服务器。
  VlssuSkin:

    # 启用该验证服务器。
    # 值为 'false' 时将不添加该 Yggdrasil 账户验证服务器到混合登入系统中去，将拒绝一切使用该 Yggdrasil 账户验证服务器的玩家登入游戏。
    # 默认值 'true'
    enable: true

    # 该账户验证服务器中的别称。
    # 不用于父节点名称，此节点的值可以随意修改。
    # 必填值，在 Bukkit 服务端中作为变量传递。
    name: "VLssuSkin.cn"

    # Yggdrasil 账户验证服务器的基本属性和信息设置。
    body:

      # Yggdrasil 账户验证服务器服务端 hasJoined 阶段部分验证请求链接设置。
      # 此节点必须指定完整的请求链接。
      # 其中 GET 请求中的占位变量 {username} 表示 username，占位变量 {serverId} 表示 serverId，
      #        占位变量 {passIpContent} 表示 passIpContent 节点所设置的内容。
      # 请求的 URL 对大小写敏感，设置需谨慎！
      # 一些例子:
      #      GET: "https://example.com/session/minecraft/hasJoined?username={username}&serverId={serverId}{passIpContent}"
      #      GET: "https://example.com/session/minecraft/hasJoined?username={username}&serverId={serverId}"
      #      POST: "https://example.com/session/minecraft/hasJoined"
      # 必填值
      url: "https://skin.vlssu.com/api/yggdrasil/sessionserver/session/minecraft/hasJoined?username={username}&serverId={serverId}{passIpContent}"

      # hasJoined 阶段使用 POST 请求的方式验证账户身份。
      # 绝大多数下， Yggdrasil 账户验证服务器 hasJoined 阶段都采用 GET 请求方式验证用户数据的，
      # 如果你不了解当前 Yggdrasil 验证流程的话，请勿擅自改动它。
      # 默认值 'false'
      postMode: false

      # hasJoined 阶段是否向 Yggdrasil 账户验证服务器传递用户 IP 信息，如果存在。
      # 默认值 'false'
      passIp: true

      # 设置 url 节点 {passIpContent} 变量内容，
      # 其中，变量 {ip} 为所获取到的 IP 信息。
      # 仅当 passIp 节点为 true 时此节点有效。
      # 请求的 URL 对大小写敏感，设置需谨慎！
      # 请留意字符串拼接的特殊值 '&' 和 ', '
      # 一些例子:
      #      GET: '&ip={ip}'
      #      POST: ', "ip":"{ip}"'
      # 默认值 '&ip={ip}'
      passIpContent: "&ip={ip}"

      # 设置 post 的请求内容。
      # 其中 POST 请求中的占位变量 {username} 表示 username，占位变量 {serverId} 表示 serverId，
      #        占位变量 {passIpContent} 表示 passIpContent 节点所设置的内容。
      # 请求的 URL 对大小写敏感，设置需谨慎！
      # 一些例子:
      #        '{"username":"{username}", "serverId":"{serverId}"{passIpContent}}'
      #        '{"username":"{username}", "serverId":"{serverId}"}'
      # 默认值 '{"username":"{username}", "serverId":"{serverId}"}'
      postContent: '{"username":"{username}", "serverId":"{serverId}"}'

    # 设置玩家首次登入后游戏内的 UUID 生成规则
    # 目前只支持以下值:
    #   DEFAULT   - 使用 Yggdrasil 账户证服务器提供的在线 UUID
    #   OFFLINE   - 自动生成离线 UUID
    #   RANDOM    - 随机 UUID
    # 请谨慎设置和修改此节点，避免增加日后维护的心智负担。
    # 为避免触发 Paper 端的某些机制，强烈建议此值为 DEFAULT
    # 默认值 'DEFAULT'
    convUuid: DEFAULT

    # 当玩家首次登入时分配到的 UUID 已被使用，自动更正到随机的 UUID。
    # 请尽量保持此值为 true ，除非您了解后果是什么。
    # 默认值 'true'
    convRepeat: true

    # 玩家允许设置的用户名正则。
    # 若不匹配将会拒绝当前玩家的登入请求
    # 如果此值留空或未设置，则应用根节点下 'nameAllowedRegular' 节点值。
    # 默认值 ''
    nameAllowedRegular: ''

    # 是否为当前验证服务器单独开启白名单。
    # 当全局白名单为 true 时，此节点强制为 true。
    # 默认值: false
    whitelist: false

    # 设置占线登入机制，登入时游戏内存在有相同游戏内 UUID 的玩家时
    # 若为 false 将把游戏内玩家踢出，允许验证中的玩家登入（原版默认）
    # 若为 true 则拒绝当前的登入请求
    # 默认值: false
    refuseRepeatedLogin: false

    # 验证错误重试次数
    # 默认值: 1
    authRetry: 2

    # 皮肤修复规则，用来解决不同 Yggdrasil 账户验证服务器下的皮肤不可见问题。
    #    比如使用 Minecraft 原版验证服务器的玩家无法看到使用第三方外置验证登入玩家的皮肤。
    # 目前只支持设置以下值:
    #   OFF       - 关闭这个功能
    #   LOGIN     - 占用登入时间进行皮肤修复操作（修复时间过长会导致登入超时）
    #   ASYNC     - 登入后修复（修复成功后需要重新连接服务器）
    # 系统将会自动过滤掉皮肤源域名为 '*.minecraft.net' 的情况
    # 皮肤修复服务器来自 'mineskin.org'
    # 默认值 'OFF'
    skinRestorer: ASYNC

    # 皮肤修复错误重试次数
    # 默认值: 2
    skinRestorerRetry: 2

  womadao:

    # 启用该验证服务器。
    # 值为 'false' 时将不添加该 Yggdrasil 账户验证服务器到混合登入系统中去，将拒绝一切使用该 Yggdrasil 账户验证服务器的玩家登入游戏。
    # 默认值 'true'
    enable: false

    # 该账户验证服务器中的别称。
    # 不用于父节点名称，此节点的值可以随意修改。
    # 必填值，在 Bukkit 服务端中作为变量传递。
    name: "skin.womadao.top"

    # Yggdrasil 账户验证服务器的基本属性和信息设置。
    body:

      # Yggdrasil 账户验证服务器服务端 hasJoined 阶段部分验证请求链接设置。
      # 此节点必须指定完整的请求链接。
      # 其中 GET 请求中的占位变量 {username} 表示 username，占位变量 {serverId} 表示 serverId，
      #        占位变量 {passIpContent} 表示 passIpContent 节点所设置的内容。
      # 请求的 URL 对大小写敏感，设置需谨慎！
      # 一些例子:
      #      GET: "https://example.com/session/minecraft/hasJoined?username={username}&serverId={serverId}{passIpContent}"
      #      GET: "https://example.com/session/minecraft/hasJoined?username={username}&serverId={serverId}"
      #      POST: "https://example.com/session/minecraft/hasJoined"
      # 必填值
      url: "https://skin.womadao.top/api/yggdrasil/sessionserver/session/minecraft/hasJoined?username={username}&serverId={serverId}{passIpContent}"

      # hasJoined 阶段使用 POST 请求的方式验证账户身份。
      # 绝大多数下， Yggdrasil 账户验证服务器 hasJoined 阶段都采用 GET 请求方式验证用户数据的，
      # 如果你不了解当前 Yggdrasil 验证流程的话，请勿擅自改动它。
      # 默认值 'false'
      postMode: false

      # hasJoined 阶段是否向 Yggdrasil 账户验证服务器传递用户 IP 信息，如果存在。
      # 默认值 'false'
      passIp: true

      # 设置 url 节点 {passIpContent} 变量内容，
      # 其中，变量 {ip} 为所获取到的 IP 信息。
      # 仅当 passIp 节点为 true 时此节点有效。
      # 请求的 URL 对大小写敏感，设置需谨慎！
      # 请留意字符串拼接的特殊值 '&' 和 ', '
      # 一些例子:
      #      GET: '&ip={ip}'
      #      POST: ', "ip":"{ip}"'
      # 默认值 '&ip={ip}'
      passIpContent: "&ip={ip}"

      # 设置 post 的请求内容。
      # 其中 POST 请求中的占位变量 {username} 表示 username，占位变量 {serverId} 表示 serverId，
      #        占位变量 {passIpContent} 表示 passIpContent 节点所设置的内容。
      # 请求的 URL 对大小写敏感，设置需谨慎！
      # 一些例子:
      #        '{"username":"{username}", "serverId":"{serverId}"{passIpContent}}'
      #        '{"username":"{username}", "serverId":"{serverId}"}'
      # 默认值 '{"username":"{username}", "serverId":"{serverId}"}'
      postContent: '{"username":"{username}", "serverId":"{serverId}"}'

    # 设置玩家首次登入后游戏内的 UUID 生成规则
    # 目前只支持以下值:
    #   DEFAULT   - 使用 Yggdrasil 账户证服务器提供的在线 UUID
    #   OFFLINE   - 自动生成离线 UUID
    #   RANDOM    - 随机 UUID
    # 请谨慎设置和修改此节点，避免增加日后维护的心智负担。
    # 为避免触发 Paper 端的某些机制，强烈建议此值为 DEFAULT
    # 默认值 'DEFAULT'
    convUuid: DEFAULT

    # 当玩家首次登入时分配到的 UUID 已被使用，自动更正到随机的 UUID。
    # 请尽量保持此值为 true ，除非您了解后果是什么。
    # 默认值 'true'
    convRepeat: true

    # 玩家允许设置的用户名正则。
    # 若不匹配将会拒绝当前玩家的登入请求
    # 如果此值留空或未设置，则应用根节点下 'nameAllowedRegular' 节点值。
    # 默认值 ''
    nameAllowedRegular: ''

    # 是否为当前验证服务器单独开启白名单。
    # 当全局白名单为 true 时，此节点强制为 true。
    # 默认值: false
    whitelist: false

    # 设置占线登入机制，登入时游戏内存在有相同游戏内 UUID 的玩家时
    # 若为 false 将把游戏内玩家踢出，允许验证中的玩家登入（原版默认）
    # 若为 true 则拒绝当前的登入请求
    # 默认值: false
    refuseRepeatedLogin: false

    # 验证错误重试次数
    # 默认值: 1
    authRetry: 2

    # 皮肤修复规则，用来解决不同 Yggdrasil 账户验证服务器下的皮肤不可见问题。
    #    比如使用 Minecraft 原版验证服务器的玩家无法看到使用第三方外置验证登入玩家的皮肤。
    # 目前只支持设置以下值:
    #   OFF       - 关闭这个功能
    #   LOGIN     - 占用登入时间进行皮肤修复操作（修复时间过长会导致登入超时）
    #   ASYNC     - 登入后修复（修复成功后需要重新连接服务器）
    # 系统将会自动过滤掉皮肤源域名为 '*.minecraft.net' 的情况
    # 皮肤修复服务器来自 'mineskin.org'
    # 默认值 'OFF'
    skinRestorer: ASYNC

    # 皮肤修复错误重试次数
    # 默认值: 2
    skinRestorerRetry: 2

  # 此节点代表 Minecraft 原版验证
  official:
    name: "MoJang正版"
    body:
      url: "https://sessionserver.mojang.com/session/minecraft/hasJoined?username={username}&serverId={serverId}{passIpContent}"

# 设置所有网络请求的超时时间
# 默认值 '10000'
servicesTimeOut: 10000

# 全局白名单开关
# 默认值 'true'
whitelist: false

# 玩家允许设置的用户名正则，不匹配将会拒绝登入请求。
# 当当前 Yggdrasil 账户验证服务器设置中对应设置节点存在值时，此节点对于该验证服务器无效。
# 默认值 '^[0-9a-zA-Z_]{1,16}$'
nameAllowedRegular: '^[0-9a-zA-Z_]{1,16}$'

  # 前缀
  # 默认值 'multilogin'
  prefix: 'multilogin'
```

### 日志

```
[2022-06-19 - 13:21:17] [Velocity Async Event Executor - #0 - INFO]: 加载文件: config.yml
[2022-06-19 - 13:21:17] [Velocity Async Event Executor - #0 - INFO]: 添加 Yggdrasil 账户验证服务器 VLssuSkin.cn(VlssuSkin)。
[2022-06-19 - 13:21:17] [Velocity Async Event Executor - #0 - INFO]: 添加 Yggdrasil 账户验证服务器 skin.womadao.top(womadao), 但未启用它。
[2022-06-19 - 13:21:17] [Velocity Async Event Executor - #0 - INFO]: 添加 Yggdrasil 账户验证服务器 MoJang正版(official)。
[2022-06-19 - 13:21:17] [Velocity Async Event Executor - #0 - DEBUG]: Database url(H2): jdbc:h2:/data/www/mcsmanager/server/server_core/velocity/plugins/multilogin/multilogin;TRACE_LEVEL_FILE=0;TRACE_LEVEL_SYSTEM_OUT=0
[2022-06-19 - 13:21:17] [Velocity Async Event Executor - #0 - INFO]: 成功连接到 H2 数据库
[2022-06-19 - 13:21:18] [Velocity Async Event Executor - #0 - DEBUG]: bStats enabled
[2022-06-19 - 13:21:18] [Velocity Async Event Executor - #0 - INFO]: 插件加载完毕
[2022-06-19 - 13:28:20] [MultiLogin Async #1 - DEBUG]: bStats submit error
java.io.IOException: Server returned HTTP response code: 429 for URL: https://bStats.org/submitData/bukkit
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at moe.caa.multilogin.core.main.MetricsLite.sendData(MetricsLite.java:186) ~[?:?]
	at moe.caa.multilogin.core.main.MetricsLite.senDataWithRetry(MetricsLite.java:148) ~[?:?]
	at moe.caa.multilogin.core.main.MetricsLite.submitData(MetricsLite.java:135) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-06-19 - 13:35:21] [MultiLogin Async #2 - DEBUG]: receive:
[2022-06-19 - 13:35:21] [MultiLogin Async #2 - DEBUG]: bStats submit success
```

### 复现步骤

1. 使用 velocity-3.1.2-SNAPSHOT-154.jar 
2. 使用1.18.2或1.19进入

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [ ] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)
